sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-test npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-185187793419"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY