services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "5001:3000"
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
    command: ["npm", "run", "test"]